# Generated by Django 2.2 on 2019-04-08 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0002_auto_20190408_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tite',
            new_name='title',
        ),
    ]
